### PR TITLE
feat: use comments instead of checks

### PR DESCRIPTION
**Pull request by ruisaraiva19**
BREAKING CHANGE: checks are no longer used in favor of comments

When using the `GITHUB_TOKEN` to authenticate actions, no workflows will run after pull requests get merged.

To trigger workflow runs, a [Private Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) should be used to authenticate with an account other than the one behind the `GITHUB_TOKEN` token.

Checks can only be created by `GITHUB_TOKEN` or GitHub Apps, so a Private Access Token won't work.

To overcome this limitation, using comments in place of checks to provide feedback on the pull request is a simple solution done on this pull request.

### CODE REVIEW

**Comment by gr2m** [comment]
> Checks can only be created by `GITHUB_TOKEN` or GitHub Apps, so a Private Access Token won't work.

Are you sure that's true? It used to work. Instead of checks we could use commit statuses, too, if these work with PATs

**Comment by gr2m** [comment]
Actually I think what we can do now is add a summary to GitHub Action builds:
https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

Maybe that's the best option for us?

**Comment by ruisaraiva19** [comment]
> Actually I think what we can do now is add a summary to GitHub Action builds: [github.blog/2022-05-09-supercharging-github-actions-with-job-summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)
> 
> Maybe that's the best option for us?

Hum, that looks good but it will not show inside pull requests any message regarding the merge schedule, right?

**Comment by gr2m** [comment]
> it will not show inside pull requests any message regarding the merge schedule, right?

I think you are right, I don't think the check run status message is adjustable yet, and it's only shown on the workflow build Summary, but when you click on the "Details" link it shows the job logs, so you'll need another click to see the Job summary.

So yeah I'm open to try it your way, can we test it out before merging the PR?

**Comment by gr2m** [comment]
I invited you to the repo: https://github.com/gr2m/merge-schedule-action/invitations

Once you accept, you should be able to re-create the PR using a local branch for testing. Welcome aboard :)

**Comment by ruisaraiva19** [comment]
> I invited you to the repo: [gr2m/merge-schedule-action/invitations](https://github.com/gr2m/merge-schedule-action/invitations)
> 
> Once you accept, you should be able to re-create the PR using a local branch for testing. Welcome aboard :)

Thanks for the invite!

I'll close this PR and open a new one 🙂

**Pull request closed without merging**
