### PR TITLE
Add ability to change merge method

### LINKED ISSUE #25: Add ability to preform a squash commit
We generally use squash commits in our project. Would this be possible to add to this action? Currently I get an error when merge commits have been disabled on the project.

### PR DESCRIPTION
**Pull request by cbetta**
* Add input option to action.yml, defining new possible  values and
  default value
* Read new input in JS and pass desired merge method to Oktokit
* Update documentation to highlight new input option

fixes #25

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Looks good to me, thank you 👍🏼

**Comment by cbetta** [comment]
Thank you @gr2m. Would you mind adding the `hacktoberfest-accepted` label to this PR? I didn't initially work on this for that reason but it does add to my PRs for the month :)

**Comment by gr2m** [comment]
sure thing 👍🏼

**Pull request merged**
